name: Publish release to NuGet

inputs:
  dotnet-version:
    required: true
  nuget-token:
    required: true
  project-path:
    required: true
  nuget-directory:
    required: true
  nuspec-file:
    required: true

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Setup Mono
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Create NuGet packages
      shell: pwsh
      run: nuget pack ${{ inputs.nuspec-file }} -OutputDirectory ${{ inputs.nuget-directory }}

    - name: Publish NuGet packages
      shell: pwsh
      run: |
        foreach($file in (Get-ChildItem "${{ inputs.nuget-directory }}" -Recurse -Include *.nupkg)) {
            nuget push $file -ApiKey "${{ inputs.nuget-token }}" -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NonInteractive
        }
        