name: Publish release to NuGet

inputs:
  dotnet-version:
    required: true
  nuget-token:
    required: true
  project-path:
    required: true
  nuget-directory:
    required: true
  nuspec-file:
    required: true

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Create NuGet packages
      shell: pwsh
      env:
        NUSPEC_FILE: ${{ inputs.nuspec-file }}
        NUGET_DIRECTORY: ${{ inputs.nuget-directory }}
      run: nuget pack $env:NUSPEC_FILE -OutputDirectory $env:NUGET_DIRECTORY

    - name: Publish NuGet packages
      shell: pwsh
      env:
        NUGET_DIRECTORY: ${{ inputs.nuget-directory }}
        NUGET_TOKEN: ${{ inputs.nuget-token }}
      run: |
        foreach($file in (Get-ChildItem "$env:NUGET_DIRECTORY" -Recurse -Include *.nupkg)) {
            nuget push $file -ApiKey "$env:NUGET_TOKEN" -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NonInteractive
        }
        