#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidTestApp.Resource", IsApplication=true)]

namespace AndroidTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Auth0.OidcClient.Resource.Attribute.font = global::AndroidTestApp.Resource.Attribute.font;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderAuthority = global::AndroidTestApp.Resource.Attribute.fontProviderAuthority;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderCerts = global::AndroidTestApp.Resource.Attribute.fontProviderCerts;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderFetchStrategy = global::AndroidTestApp.Resource.Attribute.fontProviderFetchStrategy;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderFetchTimeout = global::AndroidTestApp.Resource.Attribute.fontProviderFetchTimeout;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderPackage = global::AndroidTestApp.Resource.Attribute.fontProviderPackage;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderQuery = global::AndroidTestApp.Resource.Attribute.fontProviderQuery;
			global::Auth0.OidcClient.Resource.Attribute.fontStyle = global::AndroidTestApp.Resource.Attribute.fontStyle;
			global::Auth0.OidcClient.Resource.Attribute.fontWeight = global::AndroidTestApp.Resource.Attribute.fontWeight;
			global::Auth0.OidcClient.Resource.Boolean.abc_action_bar_embed_tabs = global::AndroidTestApp.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Auth0.OidcClient.Resource.Color.notification_action_color_filter = global::AndroidTestApp.Resource.Color.notification_action_color_filter;
			global::Auth0.OidcClient.Resource.Color.notification_icon_bg_color = global::AndroidTestApp.Resource.Color.notification_icon_bg_color;
			global::Auth0.OidcClient.Resource.Color.ripple_material_light = global::AndroidTestApp.Resource.Color.ripple_material_light;
			global::Auth0.OidcClient.Resource.Color.secondary_text_default_material_light = global::AndroidTestApp.Resource.Color.secondary_text_default_material_light;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_inset_horizontal_material = global::AndroidTestApp.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_inset_vertical_material = global::AndroidTestApp.Resource.Dimension.compat_button_inset_vertical_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_padding_horizontal_material = global::AndroidTestApp.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_padding_vertical_material = global::AndroidTestApp.Resource.Dimension.compat_button_padding_vertical_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_control_corner_material = global::AndroidTestApp.Resource.Dimension.compat_control_corner_material;
			global::Auth0.OidcClient.Resource.Dimension.notification_action_icon_size = global::AndroidTestApp.Resource.Dimension.notification_action_icon_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_action_text_size = global::AndroidTestApp.Resource.Dimension.notification_action_text_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_big_circle_margin = global::AndroidTestApp.Resource.Dimension.notification_big_circle_margin;
			global::Auth0.OidcClient.Resource.Dimension.notification_content_margin_start = global::AndroidTestApp.Resource.Dimension.notification_content_margin_start;
			global::Auth0.OidcClient.Resource.Dimension.notification_large_icon_height = global::AndroidTestApp.Resource.Dimension.notification_large_icon_height;
			global::Auth0.OidcClient.Resource.Dimension.notification_large_icon_width = global::AndroidTestApp.Resource.Dimension.notification_large_icon_width;
			global::Auth0.OidcClient.Resource.Dimension.notification_main_column_padding_top = global::AndroidTestApp.Resource.Dimension.notification_main_column_padding_top;
			global::Auth0.OidcClient.Resource.Dimension.notification_media_narrow_margin = global::AndroidTestApp.Resource.Dimension.notification_media_narrow_margin;
			global::Auth0.OidcClient.Resource.Dimension.notification_right_icon_size = global::AndroidTestApp.Resource.Dimension.notification_right_icon_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_right_side_padding_top = global::AndroidTestApp.Resource.Dimension.notification_right_side_padding_top;
			global::Auth0.OidcClient.Resource.Dimension.notification_small_icon_background_padding = global::AndroidTestApp.Resource.Dimension.notification_small_icon_background_padding;
			global::Auth0.OidcClient.Resource.Dimension.notification_small_icon_size_as_large = global::AndroidTestApp.Resource.Dimension.notification_small_icon_size_as_large;
			global::Auth0.OidcClient.Resource.Dimension.notification_subtext_size = global::AndroidTestApp.Resource.Dimension.notification_subtext_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_top_pad = global::AndroidTestApp.Resource.Dimension.notification_top_pad;
			global::Auth0.OidcClient.Resource.Dimension.notification_top_pad_large_text = global::AndroidTestApp.Resource.Dimension.notification_top_pad_large_text;
			global::Auth0.OidcClient.Resource.Drawable.notification_action_background = global::AndroidTestApp.Resource.Drawable.notification_action_background;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg = global::AndroidTestApp.Resource.Drawable.notification_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low = global::AndroidTestApp.Resource.Drawable.notification_bg_low;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low_normal = global::AndroidTestApp.Resource.Drawable.notification_bg_low_normal;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low_pressed = global::AndroidTestApp.Resource.Drawable.notification_bg_low_pressed;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_normal = global::AndroidTestApp.Resource.Drawable.notification_bg_normal;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_normal_pressed = global::AndroidTestApp.Resource.Drawable.notification_bg_normal_pressed;
			global::Auth0.OidcClient.Resource.Drawable.notification_icon_background = global::AndroidTestApp.Resource.Drawable.notification_icon_background;
			global::Auth0.OidcClient.Resource.Drawable.notification_template_icon_bg = global::AndroidTestApp.Resource.Drawable.notification_template_icon_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_template_icon_low_bg = global::AndroidTestApp.Resource.Drawable.notification_template_icon_low_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_tile_bg = global::AndroidTestApp.Resource.Drawable.notification_tile_bg;
			global::Auth0.OidcClient.Resource.Drawable.notify_panel_notification_icon_bg = global::AndroidTestApp.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Auth0.OidcClient.Resource.Id.action_container = global::AndroidTestApp.Resource.Id.action_container;
			global::Auth0.OidcClient.Resource.Id.action_divider = global::AndroidTestApp.Resource.Id.action_divider;
			global::Auth0.OidcClient.Resource.Id.action_image = global::AndroidTestApp.Resource.Id.action_image;
			global::Auth0.OidcClient.Resource.Id.action_text = global::AndroidTestApp.Resource.Id.action_text;
			global::Auth0.OidcClient.Resource.Id.actions = global::AndroidTestApp.Resource.Id.actions;
			global::Auth0.OidcClient.Resource.Id.async = global::AndroidTestApp.Resource.Id.async;
			global::Auth0.OidcClient.Resource.Id.blocking = global::AndroidTestApp.Resource.Id.blocking;
			global::Auth0.OidcClient.Resource.Id.chronometer = global::AndroidTestApp.Resource.Id.chronometer;
			global::Auth0.OidcClient.Resource.Id.forever = global::AndroidTestApp.Resource.Id.forever;
			global::Auth0.OidcClient.Resource.Id.icon = global::AndroidTestApp.Resource.Id.icon;
			global::Auth0.OidcClient.Resource.Id.icon_group = global::AndroidTestApp.Resource.Id.icon_group;
			global::Auth0.OidcClient.Resource.Id.info = global::AndroidTestApp.Resource.Id.info;
			global::Auth0.OidcClient.Resource.Id.italic = global::AndroidTestApp.Resource.Id.italic;
			global::Auth0.OidcClient.Resource.Id.line1 = global::AndroidTestApp.Resource.Id.line1;
			global::Auth0.OidcClient.Resource.Id.line3 = global::AndroidTestApp.Resource.Id.line3;
			global::Auth0.OidcClient.Resource.Id.normal = global::AndroidTestApp.Resource.Id.normal;
			global::Auth0.OidcClient.Resource.Id.notification_background = global::AndroidTestApp.Resource.Id.notification_background;
			global::Auth0.OidcClient.Resource.Id.notification_main_column = global::AndroidTestApp.Resource.Id.notification_main_column;
			global::Auth0.OidcClient.Resource.Id.notification_main_column_container = global::AndroidTestApp.Resource.Id.notification_main_column_container;
			global::Auth0.OidcClient.Resource.Id.right_icon = global::AndroidTestApp.Resource.Id.right_icon;
			global::Auth0.OidcClient.Resource.Id.right_side = global::AndroidTestApp.Resource.Id.right_side;
			global::Auth0.OidcClient.Resource.Id.text = global::AndroidTestApp.Resource.Id.text;
			global::Auth0.OidcClient.Resource.Id.text2 = global::AndroidTestApp.Resource.Id.text2;
			global::Auth0.OidcClient.Resource.Id.time = global::AndroidTestApp.Resource.Id.time;
			global::Auth0.OidcClient.Resource.Id.title = global::AndroidTestApp.Resource.Id.title;
			global::Auth0.OidcClient.Resource.Integer.status_bar_notification_info_maxnum = global::AndroidTestApp.Resource.Integer.status_bar_notification_info_maxnum;
			global::Auth0.OidcClient.Resource.Layout.notification_action = global::AndroidTestApp.Resource.Layout.notification_action;
			global::Auth0.OidcClient.Resource.Layout.notification_action_tombstone = global::AndroidTestApp.Resource.Layout.notification_action_tombstone;
			global::Auth0.OidcClient.Resource.Layout.notification_template_custom_big = global::AndroidTestApp.Resource.Layout.notification_template_custom_big;
			global::Auth0.OidcClient.Resource.Layout.notification_template_icon_group = global::AndroidTestApp.Resource.Layout.notification_template_icon_group;
			global::Auth0.OidcClient.Resource.Layout.notification_template_part_chronometer = global::AndroidTestApp.Resource.Layout.notification_template_part_chronometer;
			global::Auth0.OidcClient.Resource.Layout.notification_template_part_time = global::AndroidTestApp.Resource.Layout.notification_template_part_time;
			global::Auth0.OidcClient.Resource.String.ApplicationName = global::AndroidTestApp.Resource.String.ApplicationName;
			global::Auth0.OidcClient.Resource.String.Hello = global::AndroidTestApp.Resource.String.Hello;
			global::Auth0.OidcClient.Resource.String.status_bar_notification_info_overflow = global::AndroidTestApp.Resource.String.status_bar_notification_info_overflow;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Info = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Time = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Title = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Auth0.OidcClient.Resource.Style.Widget_Compat_NotificationActionContainer = global::AndroidTestApp.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Auth0.OidcClient.Resource.Style.Widget_Compat_NotificationActionText = global::AndroidTestApp.Resource.Style.Widget_Compat_NotificationActionText;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily = global::AndroidTestApp.Resource.Styleable.FontFamily;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderAuthority = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderCerts = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderPackage = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderQuery = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont = global::AndroidTestApp.Resource.Styleable.FontFamilyFont;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_font = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_font;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_fontStyle = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_fontWeight = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f050000
			public const int abc_action_bar_embed_tabs = 2131034112;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int notification_action_color_filter = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int notification_icon_bg_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ripple_material_light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text_default_material_light = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int compat_button_inset_horizontal_material = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int compat_button_inset_vertical_material = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int compat_button_padding_horizontal_material = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int compat_button_padding_vertical_material = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int compat_control_corner_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int notification_action_icon_size = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int notification_action_text_size = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int notification_big_circle_margin = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int notification_content_margin_start = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int notification_large_icon_height = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int notification_large_icon_width = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int notification_main_column_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int notification_media_narrow_margin = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int notification_right_icon_size = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int notification_right_side_padding_top = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int notification_small_icon_background_padding = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int notification_small_icon_size_as_large = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_subtext_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int notification_top_pad = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_top_pad_large_text = 2131099667;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int LoginButton = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int LogoutButton = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int UserDetailsTextView = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int action_container = 2131296269;
			
			// aapt resource value: 0x7f090019
			public const int action_divider = 2131296281;
			
			// aapt resource value: 0x7f09000e
			public const int action_image = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int action_text = 2131296271;
			
			// aapt resource value: 0x7f09001a
			public const int actions = 2131296282;
			
			// aapt resource value: 0x7f090005
			public const int async = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int blocking = 2131296262;
			
			// aapt resource value: 0x7f090018
			public const int chronometer = 2131296280;
			
			// aapt resource value: 0x7f090007
			public const int forever = 2131296263;
			
			// aapt resource value: 0x7f090011
			public const int icon = 2131296273;
			
			// aapt resource value: 0x7f09001b
			public const int icon_group = 2131296283;
			
			// aapt resource value: 0x7f090014
			public const int info = 2131296276;
			
			// aapt resource value: 0x7f090008
			public const int italic = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f090009
			public const int normal = 2131296265;
			
			// aapt resource value: 0x7f090016
			public const int notification_background = 2131296278;
			
			// aapt resource value: 0x7f090012
			public const int notification_main_column = 2131296274;
			
			// aapt resource value: 0x7f090010
			public const int notification_main_column_container = 2131296272;
			
			// aapt resource value: 0x7f090015
			public const int right_icon = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int right_side = 2131296275;
			
			// aapt resource value: 0x7f090002
			public const int text = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int text2 = 2131296259;
			
			// aapt resource value: 0x7f090017
			public const int time = 2131296279;
			
			// aapt resource value: 0x7f090004
			public const int title = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_template_custom_big = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_template_icon_group = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_part_chronometer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_part_time = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Logout = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int auth0_client_id = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int auth0_domain = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int status_bar_notification_info_overflow = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Info = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Line2 = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_Compat_NotificationActionContainer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionText = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
