#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidTestApp.Resource", IsApplication=true)]

namespace AndroidTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Auth0.OidcClient.Resource.Attribute.font = global::AndroidTestApp.Resource.Attribute.font;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderAuthority = global::AndroidTestApp.Resource.Attribute.fontProviderAuthority;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderCerts = global::AndroidTestApp.Resource.Attribute.fontProviderCerts;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderFetchStrategy = global::AndroidTestApp.Resource.Attribute.fontProviderFetchStrategy;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderFetchTimeout = global::AndroidTestApp.Resource.Attribute.fontProviderFetchTimeout;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderPackage = global::AndroidTestApp.Resource.Attribute.fontProviderPackage;
			global::Auth0.OidcClient.Resource.Attribute.fontProviderQuery = global::AndroidTestApp.Resource.Attribute.fontProviderQuery;
			global::Auth0.OidcClient.Resource.Attribute.fontStyle = global::AndroidTestApp.Resource.Attribute.fontStyle;
			global::Auth0.OidcClient.Resource.Attribute.fontWeight = global::AndroidTestApp.Resource.Attribute.fontWeight;
			global::Auth0.OidcClient.Resource.Color.notification_action_color_filter = global::AndroidTestApp.Resource.Color.notification_action_color_filter;
			global::Auth0.OidcClient.Resource.Color.notification_icon_bg_color = global::AndroidTestApp.Resource.Color.notification_icon_bg_color;
			global::Auth0.OidcClient.Resource.Color.ripple_material_light = global::AndroidTestApp.Resource.Color.ripple_material_light;
			global::Auth0.OidcClient.Resource.Color.secondary_text_default_material_light = global::AndroidTestApp.Resource.Color.secondary_text_default_material_light;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_inset_horizontal_material = global::AndroidTestApp.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_inset_vertical_material = global::AndroidTestApp.Resource.Dimension.compat_button_inset_vertical_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_padding_horizontal_material = global::AndroidTestApp.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_button_padding_vertical_material = global::AndroidTestApp.Resource.Dimension.compat_button_padding_vertical_material;
			global::Auth0.OidcClient.Resource.Dimension.compat_control_corner_material = global::AndroidTestApp.Resource.Dimension.compat_control_corner_material;
			global::Auth0.OidcClient.Resource.Dimension.notification_action_icon_size = global::AndroidTestApp.Resource.Dimension.notification_action_icon_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_action_text_size = global::AndroidTestApp.Resource.Dimension.notification_action_text_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_big_circle_margin = global::AndroidTestApp.Resource.Dimension.notification_big_circle_margin;
			global::Auth0.OidcClient.Resource.Dimension.notification_content_margin_start = global::AndroidTestApp.Resource.Dimension.notification_content_margin_start;
			global::Auth0.OidcClient.Resource.Dimension.notification_large_icon_height = global::AndroidTestApp.Resource.Dimension.notification_large_icon_height;
			global::Auth0.OidcClient.Resource.Dimension.notification_large_icon_width = global::AndroidTestApp.Resource.Dimension.notification_large_icon_width;
			global::Auth0.OidcClient.Resource.Dimension.notification_main_column_padding_top = global::AndroidTestApp.Resource.Dimension.notification_main_column_padding_top;
			global::Auth0.OidcClient.Resource.Dimension.notification_media_narrow_margin = global::AndroidTestApp.Resource.Dimension.notification_media_narrow_margin;
			global::Auth0.OidcClient.Resource.Dimension.notification_right_icon_size = global::AndroidTestApp.Resource.Dimension.notification_right_icon_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_right_side_padding_top = global::AndroidTestApp.Resource.Dimension.notification_right_side_padding_top;
			global::Auth0.OidcClient.Resource.Dimension.notification_small_icon_background_padding = global::AndroidTestApp.Resource.Dimension.notification_small_icon_background_padding;
			global::Auth0.OidcClient.Resource.Dimension.notification_small_icon_size_as_large = global::AndroidTestApp.Resource.Dimension.notification_small_icon_size_as_large;
			global::Auth0.OidcClient.Resource.Dimension.notification_subtext_size = global::AndroidTestApp.Resource.Dimension.notification_subtext_size;
			global::Auth0.OidcClient.Resource.Dimension.notification_top_pad = global::AndroidTestApp.Resource.Dimension.notification_top_pad;
			global::Auth0.OidcClient.Resource.Dimension.notification_top_pad_large_text = global::AndroidTestApp.Resource.Dimension.notification_top_pad_large_text;
			global::Auth0.OidcClient.Resource.Drawable.notification_action_background = global::AndroidTestApp.Resource.Drawable.notification_action_background;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg = global::AndroidTestApp.Resource.Drawable.notification_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low = global::AndroidTestApp.Resource.Drawable.notification_bg_low;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low_normal = global::AndroidTestApp.Resource.Drawable.notification_bg_low_normal;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_low_pressed = global::AndroidTestApp.Resource.Drawable.notification_bg_low_pressed;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_normal = global::AndroidTestApp.Resource.Drawable.notification_bg_normal;
			global::Auth0.OidcClient.Resource.Drawable.notification_bg_normal_pressed = global::AndroidTestApp.Resource.Drawable.notification_bg_normal_pressed;
			global::Auth0.OidcClient.Resource.Drawable.notification_icon_background = global::AndroidTestApp.Resource.Drawable.notification_icon_background;
			global::Auth0.OidcClient.Resource.Drawable.notification_template_icon_bg = global::AndroidTestApp.Resource.Drawable.notification_template_icon_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_template_icon_low_bg = global::AndroidTestApp.Resource.Drawable.notification_template_icon_low_bg;
			global::Auth0.OidcClient.Resource.Drawable.notification_tile_bg = global::AndroidTestApp.Resource.Drawable.notification_tile_bg;
			global::Auth0.OidcClient.Resource.Drawable.notify_panel_notification_icon_bg = global::AndroidTestApp.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Auth0.OidcClient.Resource.Id.action_container = global::AndroidTestApp.Resource.Id.action_container;
			global::Auth0.OidcClient.Resource.Id.action_divider = global::AndroidTestApp.Resource.Id.action_divider;
			global::Auth0.OidcClient.Resource.Id.action_image = global::AndroidTestApp.Resource.Id.action_image;
			global::Auth0.OidcClient.Resource.Id.action_text = global::AndroidTestApp.Resource.Id.action_text;
			global::Auth0.OidcClient.Resource.Id.actions = global::AndroidTestApp.Resource.Id.actions;
			global::Auth0.OidcClient.Resource.Id.async = global::AndroidTestApp.Resource.Id.async;
			global::Auth0.OidcClient.Resource.Id.blocking = global::AndroidTestApp.Resource.Id.blocking;
			global::Auth0.OidcClient.Resource.Id.chronometer = global::AndroidTestApp.Resource.Id.chronometer;
			global::Auth0.OidcClient.Resource.Id.forever = global::AndroidTestApp.Resource.Id.forever;
			global::Auth0.OidcClient.Resource.Id.icon = global::AndroidTestApp.Resource.Id.icon;
			global::Auth0.OidcClient.Resource.Id.icon_group = global::AndroidTestApp.Resource.Id.icon_group;
			global::Auth0.OidcClient.Resource.Id.info = global::AndroidTestApp.Resource.Id.info;
			global::Auth0.OidcClient.Resource.Id.italic = global::AndroidTestApp.Resource.Id.italic;
			global::Auth0.OidcClient.Resource.Id.line1 = global::AndroidTestApp.Resource.Id.line1;
			global::Auth0.OidcClient.Resource.Id.line3 = global::AndroidTestApp.Resource.Id.line3;
			global::Auth0.OidcClient.Resource.Id.normal = global::AndroidTestApp.Resource.Id.normal;
			global::Auth0.OidcClient.Resource.Id.notification_background = global::AndroidTestApp.Resource.Id.notification_background;
			global::Auth0.OidcClient.Resource.Id.notification_main_column = global::AndroidTestApp.Resource.Id.notification_main_column;
			global::Auth0.OidcClient.Resource.Id.notification_main_column_container = global::AndroidTestApp.Resource.Id.notification_main_column_container;
			global::Auth0.OidcClient.Resource.Id.right_icon = global::AndroidTestApp.Resource.Id.right_icon;
			global::Auth0.OidcClient.Resource.Id.right_side = global::AndroidTestApp.Resource.Id.right_side;
			global::Auth0.OidcClient.Resource.Id.text = global::AndroidTestApp.Resource.Id.text;
			global::Auth0.OidcClient.Resource.Id.text2 = global::AndroidTestApp.Resource.Id.text2;
			global::Auth0.OidcClient.Resource.Id.time = global::AndroidTestApp.Resource.Id.time;
			global::Auth0.OidcClient.Resource.Id.title = global::AndroidTestApp.Resource.Id.title;
			global::Auth0.OidcClient.Resource.Integer.status_bar_notification_info_maxnum = global::AndroidTestApp.Resource.Integer.status_bar_notification_info_maxnum;
			global::Auth0.OidcClient.Resource.Layout.notification_action = global::AndroidTestApp.Resource.Layout.notification_action;
			global::Auth0.OidcClient.Resource.Layout.notification_action_tombstone = global::AndroidTestApp.Resource.Layout.notification_action_tombstone;
			global::Auth0.OidcClient.Resource.Layout.notification_template_custom_big = global::AndroidTestApp.Resource.Layout.notification_template_custom_big;
			global::Auth0.OidcClient.Resource.Layout.notification_template_icon_group = global::AndroidTestApp.Resource.Layout.notification_template_icon_group;
			global::Auth0.OidcClient.Resource.Layout.notification_template_part_chronometer = global::AndroidTestApp.Resource.Layout.notification_template_part_chronometer;
			global::Auth0.OidcClient.Resource.Layout.notification_template_part_time = global::AndroidTestApp.Resource.Layout.notification_template_part_time;
			global::Auth0.OidcClient.Resource.String.ApplicationName = global::AndroidTestApp.Resource.String.ApplicationName;
			global::Auth0.OidcClient.Resource.String.Hello = global::AndroidTestApp.Resource.String.Hello;
			global::Auth0.OidcClient.Resource.String.status_bar_notification_info_overflow = global::AndroidTestApp.Resource.String.status_bar_notification_info_overflow;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Info = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Time = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Auth0.OidcClient.Resource.Style.TextAppearance_Compat_Notification_Title = global::AndroidTestApp.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Auth0.OidcClient.Resource.Style.Widget_Compat_NotificationActionContainer = global::AndroidTestApp.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Auth0.OidcClient.Resource.Style.Widget_Compat_NotificationActionText = global::AndroidTestApp.Resource.Style.Widget_Compat_NotificationActionText;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily = global::AndroidTestApp.Resource.Styleable.FontFamily;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderAuthority = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderCerts = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderPackage = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Auth0.OidcClient.Resource.Styleable.FontFamily_fontProviderQuery = global::AndroidTestApp.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont = global::AndroidTestApp.Resource.Styleable.FontFamilyFont;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_font = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_font;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_fontStyle = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Auth0.OidcClient.Resource.Styleable.FontFamilyFont_fontWeight = global::AndroidTestApp.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int alpha = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int coordinatorLayoutStyle = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int fontVariationSettings = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int keylines = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int layout_anchor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_anchorGravity = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int layout_behavior = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int layout_dodgeInsetEdges = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int layout_insetEdge = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int layout_keyline = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int statusBarBackground = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int browser_actions_bg_grey = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int browser_actions_divider_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int browser_actions_text_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int browser_actions_title_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_action_color_filter = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_icon_bg_color = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ripple_material_light = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int secondary_text_default_material_light = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int browser_actions_context_menu_max_width = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int browser_actions_context_menu_min_padding = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int compat_button_inset_horizontal_material = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int compat_button_inset_vertical_material = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int compat_button_padding_horizontal_material = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int compat_button_padding_vertical_material = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int compat_control_corner_material = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int compat_notification_large_icon_max_height = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int compat_notification_large_icon_max_width = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int notification_action_icon_size = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int notification_action_text_size = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int notification_big_circle_margin = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int notification_content_margin_start = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int notification_large_icon_height = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int notification_large_icon_width = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int notification_main_column_padding_top = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int notification_media_narrow_margin = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int notification_right_icon_size = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int notification_right_side_padding_top = 2131034114;
			
			// aapt resource value: 0x7f050013
			public const int notification_small_icon_background_padding = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int notification_small_icon_size_as_large = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int notification_subtext_size = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int notification_top_pad = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int notification_top_pad_large_text = 2131034135;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080023
			public const int LoginButton = 2131230755;
			
			// aapt resource value: 0x7f080025
			public const int LogoutButton = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int UserButton = 2131230756;
			
			// aapt resource value: 0x7f080026
			public const int UserDetailsTextView = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int action_container = 2131230759;
			
			// aapt resource value: 0x7f080033
			public const int action_divider = 2131230771;
			
			// aapt resource value: 0x7f080028
			public const int action_image = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int action_text = 2131230761;
			
			// aapt resource value: 0x7f080034
			public const int actions = 2131230772;
			
			// aapt resource value: 0x7f080017
			public const int all = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int async = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int blocking = 2131230745;
			
			// aapt resource value: 0x7f080008
			public const int bottom = 2131230728;
			
			// aapt resource value: 0x7f08001e
			public const int browser_actions_header_text = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int browser_actions_menu_item_icon = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int browser_actions_menu_item_text = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int browser_actions_menu_items = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int browser_actions_menu_view = 2131230749;
			
			// aapt resource value: 0x7f080009
			public const int center = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int center_horizontal = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int center_vertical = 2131230731;
			
			// aapt resource value: 0x7f080032
			public const int chronometer = 2131230770;
			
			// aapt resource value: 0x7f08000c
			public const int clip_horizontal = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int clip_vertical = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int end = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int fill = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int fill_horizontal = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int fill_vertical = 2131230737;
			
			// aapt resource value: 0x7f08001a
			public const int forever = 2131230746;
			
			// aapt resource value: 0x7f08002b
			public const int icon = 2131230763;
			
			// aapt resource value: 0x7f080035
			public const int icon_group = 2131230773;
			
			// aapt resource value: 0x7f08002e
			public const int info = 2131230766;
			
			// aapt resource value: 0x7f08001b
			public const int italic = 2131230747;
			
			// aapt resource value: 0x7f080012
			public const int left = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int line1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int line3 = 2131230721;
			
			// aapt resource value: 0x7f080022
			public const int linearLayout1 = 2131230754;
			
			// aapt resource value: 0x7f080016
			public const int none = 2131230742;
			
			// aapt resource value: 0x7f08001c
			public const int normal = 2131230748;
			
			// aapt resource value: 0x7f080030
			public const int notification_background = 2131230768;
			
			// aapt resource value: 0x7f08002c
			public const int notification_main_column = 2131230764;
			
			// aapt resource value: 0x7f08002a
			public const int notification_main_column_container = 2131230762;
			
			// aapt resource value: 0x7f080013
			public const int right = 2131230739;
			
			// aapt resource value: 0x7f08002f
			public const int right_icon = 2131230767;
			
			// aapt resource value: 0x7f08002d
			public const int right_side = 2131230765;
			
			// aapt resource value: 0x7f080014
			public const int start = 2131230740;
			
			// aapt resource value: 0x7f080002
			public const int tag_transition_group = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int tag_unhandled_key_event_manager = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int tag_unhandled_key_listeners = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int text = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int text2 = 2131230726;
			
			// aapt resource value: 0x7f080031
			public const int time = 2131230769;
			
			// aapt resource value: 0x7f080007
			public const int title = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int top = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_maxnum = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int browser_actions_context_menu_page = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int browser_actions_context_menu_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_action_tombstone = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_custom_big = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_icon_group = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_part_chronometer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_part_time = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Hello = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int Login = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Logout = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int UserInfo = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int auth0_domain = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int status_bar_notification_info_overflow = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int TextAppearance_Compat_Notification = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TextAppearance_Compat_Notification_Info = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int TextAppearance_Compat_Notification_Line2 = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int TextAppearance_Compat_Notification_Time = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int TextAppearance_Compat_Notification_Title = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget_Compat_NotificationActionContainer = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Widget_Compat_NotificationActionText = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int Widget_Support_CoordinatorLayout = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771977};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
