#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Auth0.OidcClient.Resource", IsApplication=false)]

namespace Auth0.OidcClient
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int font = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int fontProviderCerts = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int fontProviderFetchStrategy = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int fontProviderFetchTimeout = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int fontProviderPackage = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int fontProviderQuery = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int fontStyle = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public static int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public static int notification_action_color_filter = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int notification_icon_bg_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int ripple_material_light = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int secondary_text_default_material_light = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public static int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int notification_action_icon_size = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int notification_action_text_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int notification_big_circle_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int notification_content_margin_start = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int notification_large_icon_height = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int notification_large_icon_width = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int notification_right_icon_size = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int notification_right_side_padding_top = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public static int notification_small_icon_background_padding = 2130968591;
			
			// aapt resource value: 0x7F040010
			public static int notification_small_icon_size_as_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public static int notification_subtext_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public static int notification_top_pad = 2130968594;
			
			// aapt resource value: 0x7F040013
			public static int notification_top_pad_large_text = 2130968595;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public static int notification_action_background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int notification_bg = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int notification_bg_low = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int notification_bg_low_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int notification_bg_low_pressed = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int notification_bg_normal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int notification_bg_normal_pressed = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int notification_icon_background = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int notification_template_icon_bg = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int notification_template_icon_low_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int notification_tile_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int notify_panel_notification_icon_bg = 2131034123;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060004
			public static int actions = 2131099652;
			
			// aapt resource value: 0x7F060000
			public static int action_container = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int action_divider = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int action_image = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int action_text = 2131099651;
			
			// aapt resource value: 0x7F060005
			public static int async = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int blocking = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int chronometer = 2131099655;
			
			// aapt resource value: 0x7F060008
			public static int forever = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int icon = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int icon_group = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int info = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int italic = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public static int line1 = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public static int line3 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public static int normal = 2131099663;
			
			// aapt resource value: 0x7F060010
			public static int notification_background = 2131099664;
			
			// aapt resource value: 0x7F060011
			public static int notification_main_column = 2131099665;
			
			// aapt resource value: 0x7F060012
			public static int notification_main_column_container = 2131099666;
			
			// aapt resource value: 0x7F060013
			public static int right_icon = 2131099667;
			
			// aapt resource value: 0x7F060014
			public static int right_side = 2131099668;
			
			// aapt resource value: 0x7F060015
			public static int text = 2131099669;
			
			// aapt resource value: 0x7F060016
			public static int text2 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public static int time = 2131099671;
			
			// aapt resource value: 0x7F060018
			public static int title = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public static int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public static int notification_action = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int notification_action_tombstone = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int notification_template_custom_big = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int notification_template_icon_group = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int notification_template_part_chronometer = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int notification_template_part_time = 2131230725;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public static int status_bar_notification_info_overflow = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public static int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public static int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public static int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public static int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public static int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public static int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public static int Widget_Compat_NotificationActionText = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006 }
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: { 0x7F010000,0x7F010007,0x7F010008 }
			public static int[] FontFamilyFont = new int[] {
					2130771968,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public static int FontFamilyFont_font = 0;
			
			// aapt resource value: 1
			public static int FontFamilyFont_fontStyle = 1;
			
			// aapt resource value: 2
			public static int FontFamilyFont_fontWeight = 2;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
