name: Build

on:
  pull_request: {}

  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2022
    env:
      DOTNET_VERSION: '9.0.200'
      ANDROID_SDK_ROOT: "C:\\Android\\android-sdk"
      ANDROID_HOME: "C:\\Android\\android-sdk"
      ANDROID_API_LEVEL: "31"
      BUILD_TOOLS_VERSION: "31.0.0"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Configure Android env (Windows)
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_ENV "ANDROID_HOME=$env:ANDROID_SDK_ROOT"
          Add-Content $env:GITHUB_ENV "ANDROID_SDK_HOME=$env:RUNNER_TEMP\android-home"
          Add-Content $env:GITHUB_PATH "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin"

      - name: Install Android platform + build-tools (Windows)
        shell: pwsh
        run: |
          sdkmanager "platforms;android-$env:ANDROID_API_LEVEL" "build-tools;$env:BUILD_TOOLS_VERSION"
          if (!(Test-Path "$env:ANDROID_SDK_ROOT\platforms\android-$env:ANDROID_API_LEVEL")) { throw "platforms missing" }
          if (!(Test-Path "$env:ANDROID_SDK_ROOT\build-tools\$env:BUILD_TOOLS_VERSION")) { throw "build-tools missing" }

      - name: workload update version
        run: dotnet workload update

      - name: Install .NET Android and iOS workload
        run: dotnet workload install android ios maui

      - name: workload update version
        run: dotnet workload update

      - name: Dotnet framework and workload versions
        run: dotnet --info

      - name: Setup NuGet
        uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4.0

      - name: Restore NuGet
        run: nuget restore Auth0.OidcClient.All.sln
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Build
        run: msbuild Auth0.OidcClient.All.sln -t:rebuild -property:Configuration=Release -property:AndroidSdkDirectory=%ANDROID_SDK_ROOT%

      - name: Tests
        run: dotnet test **\bin\**\*UnitTests.dll