name: Build

on:
  pull_request: {}

  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2022
    env:
      DOTNET_VERSION: '9.0.200'
      ANDROID_SDK_ROOT: "C:\\Android\\android-sdk"
      ANDROID_HOME: "C:\\Android\\android-sdk"
      ANDROID_API_LEVEL: "31"
      BUILD_TOOLS_VERSION: "31.0.0"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Configure Android env (Windows)
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_ENV "ANDROID_HOME=$env:ANDROID_SDK_ROOT"
          Add-Content $env:GITHUB_ENV "ANDROID_SDK_HOME=$env:RUNNER_TEMP\android-home"
          Add-Content $env:GITHUB_PATH "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin"

      - name: Install Android platform + build-tools (Windows)
        shell: pwsh
        run: |
          sdkmanager "platforms;android-$env:ANDROID_API_LEVEL" "build-tools;$env:BUILD_TOOLS_VERSION"
          if (!(Test-Path "$env:ANDROID_SDK_ROOT\platforms\android-$env:ANDROID_API_LEVEL")) { throw "platforms missing" }
          if (!(Test-Path "$env:ANDROID_SDK_ROOT\build-tools\$env:BUILD_TOOLS_VERSION")) { throw "build-tools missing" }

      - name: workload update version
        run: dotnet workload update

      - name: Install .NET Android and iOS workload
        run: dotnet workload install android ios maui

      - name: workload update version
        run: dotnet workload update

      - name: Dotnet framework and workload versions
        run: dotnet --info

      - name: Setup NuGet
        uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2.0.2

      - name: Restore NuGet
        run: nuget restore Auth0.OidcClient.All.sln
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Build
        run: msbuild Auth0.OidcClient.All.sln -t:rebuild -property:Configuration=Release -property:AndroidSdkDirectory=%ANDROID_SDK_ROOT%

      - name: Tests
        run: dotnet test **\bin\**\*UnitTests.dll