name: Generate API docs

on:
  workflow_dispatch:

  push:
    branches: ["fix/api-docs"]

permissions:
  contents: read

jobs:
  generate-docs:
    name: Generate API docs
    runs-on: windows-latest
    environment: 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Install .NET Android and iOS workload
        run: dotnet workload install android ios

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet
        run: nuget restore Auth0.OidcClient.All.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild Auth0.OidcClient.All.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Install DocFX
        run: dotnet tool install -g docfx
      
      - name: Build docs
        run: ./tools/build-docs.sh
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs