name: Publish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to release from
        required: true
        default: master

permissions:
  contents: read

jobs:
  publish-nuget:
    name: Publish to NuGet
    runs-on: windows-latest
    environment: 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Install .NET Android and iOS workload
        run: dotnet workload install android ios

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet
        run: nuget restore Auth0.OidcClient.All.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild Auth0.OidcClient.All.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build docs
        run: ./tools/build-docs.sh
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
          
      - name: NuGet pack
        run: |
          nuget pack nuget/Auth0.OidcClient.Android.nuspec
          nuget pack nuget/Auth0.OidcClient.AndroidX.nuspec
          nuget pack nuget/Auth0.OidcClient.Core.nuspec
          nuget pack nuget/Auth0.OidcClient.iOS.nuspec
          nuget pack nuget/Auth0.OidcClient.UWP.nuspec
          nuget pack nuget/Auth0.OidcClient.WinForms.nuspec
          nuget pack nuget/Auth0.OidcClient.WPF.nuspec

      - uses: actions/upload-artifact@v3
        with:
          name: drop
          path: '**/*.nupkg'

      - name: Publish release to NuGet
        run: nuget push **\*.nupkg -ApiKey ${{ env.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NonInteractive
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  # Deploy job
  deploy-docs:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 # or specific "vX.X.X" version tag for this action
        with:
          artifact_name: docs


