name: Snyk

on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
  schedule:
    - cron: "30 0 1,15 * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  check:

    name: Check for Vulnerabilities
    runs-on: windows-2022

    steps:
      - if: github.actor == 'dependabot[bot]' || github.event_name == 'merge_group'
        run: exit 0 # Skip unnecessary test runs for dependabot and merge queues. Artifically flag as successful, as this is a required check for branch protection.

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.ref }}

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.200'

      - name: workload update version
        run: dotnet workload update --version 9.0.200

      - name: Install .NET Android and iOS workload
        run: dotnet workload install android ios maui --version 9.0.200

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet
        run: nuget restore Auth0.OidcClient.All.sln

      # Install Snyk
      - run: npm install snyk -g

      # Report vulnerabilities
      - run: snyk test --file=Auth0.OidcClient.All.sln --policy-path=.snyk --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}